name: 'The name of your action here'
description: 'Provide a description here'
author: 'prod1101'

branding:
  icon: 'flag'
  color: 'red'

inputs:
  team_id:
    description: 'Team Id to generate the scores for.'
    required: true
    default: '8323'
  outfile_path:
    description: 'Filepath to print the output to'
    required: true
    default: './team-scores.md'
  prefix:
    description: 'Text to prepend to the scores'
    required: false
    default: ''

outputs:
  scores:
    description: 'The generated scores'

runs:
  using: node20
  main: dist/index.js
