name: 'CTFTime Team Scores Exporter'
description:
  'Creates an Markdown overview file including the results of your team.'
author: 'prod1101'

branding:
  icon: 'flag'
  color: 'red'

inputs:
  team_id:
    description: 'Team Id to generate the scores for.'
    required: true
    default: '8323'
  outfile_path:
    description: 'Filepath to print the output to'
    required: true
    default: './team-scores.md'
  prefix:
    description: 'Text to prepend to the scores'
    required: false
    default: ''
  suffix:
    description: 'Text to append to the scores'
    required: false
    default: ''
  percentile_colors:
    description: 'WoW colors for the percentiles'
    required: false
    default: 'false'

outputs:
  scores:
    description: 'The fetched and generated scores'

runs:
  using: node20
  main: dist/index.js
